---
- name: Extract artifact.tar.gz into /var/www/
  ansible.builtin.unarchive:
    src: /root/project/artifact.tar.gz
    dest: /
    remote_src: no
    mode: u+rwx
  become: yes

- name: Run NPM Install
  command: npm install
  become: yes

- name: Run PM2 Stop
  command: pm2 stop default
  become: yes

- name: Run PM2 Start
  command: pm2 start npm -- start
  become: yes
